server:
  port: ${port:5151}

#logging:
#  level:
#    microservice.mapper: debug

spring:
  application:
    name: micro-foot-truck
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/microservice
    username: postgres
    password: 123456
    driverClassName: org.postgresql.Driver


#  redis:
#    database: 0
#    host: localhost
#    password:
#    port: 6379



eureka:
  client:
#    registerWithEureka: true
#    fetchRegistry: true
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${eurekaServerUrl:http://123:qwe@127.0.0.1:1010/eureka/}
  instance:
    prefer-ip-address: true
    ip-address: ${ipAddress:127.0.0.1}

