insert into biz_food_truck values (1571753,'The Geez Freeze','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1565571,'MOMO INNOVATION LLC','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1565954,'Treats by the Bay LLC','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1565594,'MOMO INNOVATION LLC','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (735318,'Ziaurehman Amini','Push Cart',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1565628,'Treats by the Bay LLC','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1612646,'San Francisco Taco Truck','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1612654,'Sunset Mercantile/Outer Sunset Farmers Market & Mercantile','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1571649,'DO UC US Mobile Catering','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1591821,'Truly Food & More','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1591820,'Truly Food & More','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1565413,'MOMO INNOVATION LLC','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1565414,'MOMO INNOVATION LLC','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1565623,'Treats by the Bay LLC','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1591819,'Truly Food & More','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1585955,'Bonito Poke','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1585964,'Curry Up Now','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1598473,'San Pancho''s Tacos','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1571660,'San Francisco Carts & Concessions, Inc. DBA Stanley''s Steamers Hot Dogs','Push Cart',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1589658,'Zuri Food Facilities','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1591833,'Halal Cart of San Francisco','Push Cart',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1585952,'Bonito Poke','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1577204,'The New York Frankfurter Co. of CA, Inc. DBA: Annie''s Hot Dogs','Push Cart',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1577206,'The New York Frankfurter Co. of CA, Inc. DBA: Annie''s Hot Dogs','Push Cart',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1585966,'Curry Up Now','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1585967,'Curry Up Now','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1585954,'Bonito Poke','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1577205,'The New York Frankfurter Co. of CA, Inc. DBA: Annie''s Hot Dogs','Push Cart',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1585965,'Curry Up Now','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1585953,'Bonito Poke','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1589659,'Zuri Food Facilities','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1589647,'Philz Coffee Truck','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1589657,'Zuri Food Facilities','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1589648,'Philz Coffee Truck','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1598475,'San Pancho''s Tacos','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1598474,'San Pancho''s Tacos','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1591808,'Halal Cart, LLC','Push Cart',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1591807,'Halal Cart, LLC','Push Cart',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1591834,'Halal Cart of San Francisco','Push Cart',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1591809,'Halal Cart, LLC','Push Cart',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587393,'Truly Food & More','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587558,'Brazuca Grill','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1621287,'Street Meet','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1591824,'Cochinita','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1591823,'Cochinita','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1591822,'Cochinita','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1591825,'Cochinita','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1591827,'Cochinita','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1591829,'Cochinita','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1591840,'Tacos Rodriguez','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1591842,'Tacos Rodriguez','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1591841,'Tacos Rodriguez','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1617853,'Tacos El Flaco','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1622210,'Roadside Rotisserie Corporation / Country Grill','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1591839,'Tacos Rodriguez','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1591828,'Cochinita','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1591826,'Cochinita','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1336741,'Quan Catering','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1337426,'Liang Bai Ping','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (848184,'Reecees Soulicious','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1332942,'Mini Mobile Food Catering','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1343831,'Got Snacks','Push Cart',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1047831,'The Chef Station','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1606346,'MOMO INNOVATION LLC','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (934516,'Scotch Bonnet','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1337425,'Liang Bai Ping','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1552372,'Breakfast Embed','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1552373,'Breakfast Embed','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1575168,'Buenafe','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1571659,'San Francisco Carts & Concessions, Inc. DBA Stanley''s Steamers Hot Dogs','Push Cart',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1575155,'Papalote Inc.','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1575171,'Buenafe','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1571657,'San Francisco Carts & Concessions, Inc. DBA Stanley''s Steamers Hot Dogs','Push Cart',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1575218,'Bay Area Mobile Catering, Inc. dba. Taqueria Angelica''s','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1575170,'Buenafe','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1576237,'Natan''s Catering','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1568972,'Fillmore Square','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1568999,'Think is Good Inc.','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1568965,'CARDONA''s FOOD TRUCK','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1568971,'Fillmore Square','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1568959,'Senor Sisig','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1568960,'Senor Sisig','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1571648,'DO UC US Mobile Catering','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1571646,'DO UC US Mobile Catering','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1575216,'Bay Area Mobile Catering, Inc. dba. Taqueria Angelica''s','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1568970,'Fillmore Square','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1568948,'Senor Sisig','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1568992,'La Jefa','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1568947,'Senor Sisig','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1568998,'Think is Good Inc.','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1568951,'Senor Sisig','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1568966,'CARDONA''s FOOD TRUCK','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1568973,'Fillmore Square','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1568997,'Think is Good Inc.','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1568883,'Senor Sisig','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1568975,'California Kahve','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1568884,'Senor Sisig','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1568961,'Senor Sisig','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1569152,'Datam SF LLC dba Anzu To You','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1569145,'Casita Vegana','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1571658,'San Francisco Carts & Concessions, Inc. DBA Stanley''s Steamers Hot Dogs','Push Cart',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1571647,'DO UC US Mobile Catering','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1575217,'Bay Area Mobile Catering, Inc. dba. Taqueria Angelica''s','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1576224,'Natan''s Catering','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1575215,'Bay Area Mobile Catering, Inc. dba. Taqueria Angelica''s','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1575156,'Papalote Inc.','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1576239,'Natan''s Catering','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1576208,'Natan''s Catering','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1576216,'Natan''s Catering','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1576219,'Natan''s Catering','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587521,'Chairman SF, LLC','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1535606,'Wu Wei LLC dba MoBowl','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1576354,'San Francisco''s Hometown Creamery','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587567,'Brazuca Grill','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1589650,'Philz Coffee Truck','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1589651,'Plaza Garibaldy','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1589653,'Plaza Garibaldy','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1589660,'Zuri Food Facilities','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1589646,'Philz Coffee Truck','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1589652,'Plaza Garibaldy','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1589649,'Philz Coffee Truck','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587539,'Brazuca Grill','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587556,'Brazuca Grill','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587551,'Brazuca Grill','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587546,'Brazuca Grill','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587559,'Brazuca Grill','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587569,'Brazuca Grill','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587538,'Brazuca Grill','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587564,'Brazuca Grill','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1576225,'Natan''s Catering','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1576228,'Natan''s Catering','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1576214,'Natan''s Catering','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587562,'Brazuca Grill','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587571,'Brazuca Grill','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1576218,'Natan''s Catering','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587547,'Brazuca Grill','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587576,'Eva''s Catering','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587565,'Brazuca Grill','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587557,'Brazuca Grill','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587544,'Brazuca Grill','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587553,'Brazuca Grill','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587577,'Eva''s Catering','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587563,'Brazuca Grill','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587536,'Brazuca Grill','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587534,'Brazuca Grill','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587550,'Brazuca Grill','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1576229,'Natan''s Catering','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587543,'Brazuca Grill','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587579,'Eva''s Catering','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587545,'Brazuca Grill','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587523,'Chairman SF, LLC','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587561,'Brazuca Grill','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587575,'Eva''s Catering','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587541,'Brazuca Grill','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587566,'Brazuca Grill','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587581,'Eva''s Catering','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587552,'Brazuca Grill','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587580,'Eva''s Catering','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587522,'Chairman SF, LLC','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587537,'Brazuca Grill','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587524,'Chairman SF, LLC','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587578,'Eva''s Catering','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587549,'Brazuca Grill','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587542,'Brazuca Grill','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587570,'Brazuca Grill','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587574,'Eva''s Catering','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587568,'Brazuca Grill','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587535,'Brazuca Grill','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587554,'Brazuca Grill','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587548,'Brazuca Grill','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587555,'Brazuca Grill','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1337457,'Liang Bai Ping','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1514026,'F & C Catering','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1576230,'Natan''s Catering','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1576232,'Natan''s Catering','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587560,'Brazuca Grill','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1587540,'Brazuca Grill','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1590836,'El Alambre','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1590833,'El Alambre','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1509787,'El Gallo Jiro','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (963992,'Singh Brothers Ice Cream','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1343454,'Esmeli Catering','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1089698,'El Tonayense #60','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1590834,'El Alambre','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1590835,'El Alambre','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1514031,'F & C Catering','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1575185,'Park''s Catering','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1575191,'Park''s Catering','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1591847,'Golden Gate Halal Food','Push Cart',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1576231,'Natan''s Catering','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1514029,'F & C Catering','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1575179,'Park''s Catering','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1591779,'Street Meet','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1576375,'San Francisco''s Hometown Creamery','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1576236,'Natan''s Catering','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1591780,'Street Meet','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1535609,'Wu Wei LLC dba MoBowl','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1576386,'San Francisco''s Hometown Creamery','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1576223,'Natan''s Catering','Truck',now(),'system',now(),'system',1,0);
insert into biz_food_truck values (1576238,'Natan''s Catering','Truck',now(),'system',now(),'system',1,0);
